/*
###############################################################
#  Generated by:      Cadence Encounter 13.24-s026_1
#  OS:                Linux x86_64(Host ID ic21.cs.nthu.edu.tw)
#  Generated on:      Tue Jan 10 13:39:47 2017
#  Design:            SAO_1
#  Command:           saveNetlist SAO_pr.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : K-2015.06-SP1
// Date      : Mon Jan  9 02:00:21 2017
/////////////////////////////////////////////////////////////
module SAO_1_DW01_inc_0 (
	A, 
	SUM);
   input [13:0] A;
   output [13:0] SUM;

   // Internal wires
   wire [13:2] carry;

   ADDHXL U1_1_12 (.S(SUM[12]),
	.CO(carry[13]),
	.B(carry[12]),
	.A(A[12]));
   ADDHXL U1_1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.B(carry[5]),
	.A(A[5]));
   ADDHXL U1_1_6 (.S(SUM[6]),
	.CO(carry[7]),
	.B(carry[6]),
	.A(A[6]));
   ADDHXL U1_1_9 (.S(SUM[9]),
	.CO(carry[10]),
	.B(carry[9]),
	.A(A[9]));
   ADDHXL U1_1_8 (.S(SUM[8]),
	.CO(carry[9]),
	.B(carry[8]),
	.A(A[8]));
   ADDHXL U1_1_10 (.S(SUM[10]),
	.CO(carry[11]),
	.B(carry[10]),
	.A(A[10]));
   ADDHXL U1_1_7 (.S(SUM[7]),
	.CO(carry[8]),
	.B(carry[7]),
	.A(A[7]));
   ADDHXL U1_1_11 (.S(SUM[11]),
	.CO(carry[12]),
	.B(carry[11]),
	.A(A[11]));
   ADDHXL U1_1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.B(A[0]),
	.A(A[1]));
   ADDHXL U1_1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.B(carry[4]),
	.A(A[4]));
   ADDHXL U1_1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.B(carry[2]),
	.A(A[2]));
   ADDHXL U1_1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.B(carry[3]),
	.A(A[3]));
   CLKINVX1 U1 (.Y(SUM[0]),
	.A(A[0]));
   XOR2X1 U2 (.Y(SUM[13]),
	.B(A[13]),
	.A(carry[13]));
endmodule

module SAO_1_DW01_inc_1 (
	A, 
	SUM);
   input [13:0] A;
   output [13:0] SUM;

   // Internal wires
   wire [13:2] carry;

   ADDHXL U1_1_9 (.S(SUM[9]),
	.CO(carry[10]),
	.B(carry[9]),
	.A(A[9]));
   ADDHXL U1_1_8 (.S(SUM[8]),
	.CO(carry[9]),
	.B(carry[8]),
	.A(A[8]));
   ADDHXL U1_1_10 (.S(SUM[10]),
	.CO(carry[11]),
	.B(carry[10]),
	.A(A[10]));
   ADDHXL U1_1_11 (.S(SUM[11]),
	.CO(carry[12]),
	.B(carry[11]),
	.A(A[11]));
   ADDHXL U1_1_7 (.S(SUM[7]),
	.CO(carry[8]),
	.B(carry[7]),
	.A(A[7]));
   ADDHXL U1_1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.B(carry[4]),
	.A(A[4]));
   ADDHXL U1_1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.B(carry[2]),
	.A(A[2]));
   ADDHXL U1_1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.B(carry[3]),
	.A(A[3]));
   ADDHXL U1_1_6 (.S(SUM[6]),
	.CO(carry[7]),
	.B(carry[6]),
	.A(A[6]));
   ADDHXL U1_1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.B(A[0]),
	.A(A[1]));
   ADDHXL U1_1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.B(carry[5]),
	.A(A[5]));
   CLKINVX1 U1 (.Y(SUM[0]),
	.A(A[0]));
endmodule

module SAO_1_DW01_inc_3 (
	A, 
	SUM);
   input [6:0] A;
   output [6:0] SUM;

   // Internal wires
   wire [6:2] carry;

   ADDHXL U1_1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.B(carry[5]),
	.A(A[5]));
   ADDHXL U1_1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.B(carry[4]),
	.A(A[4]));
   ADDHXL U1_1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.B(carry[3]),
	.A(A[3]));
   ADDHXL U1_1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.B(carry[2]),
	.A(A[2]));
   ADDHXL U1_1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.B(A[0]),
	.A(A[1]));
   CLKINVX1 U1 (.Y(SUM[0]),
	.A(A[0]));
   XOR2X1 U2 (.Y(SUM[6]),
	.B(A[6]),
	.A(carry[6]));
endmodule

module SAO_1_DW01_sub_0 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] DIFF;
   output CO;

   // Internal wires
   wire [9:0] carry;
endmodule

module SAO_1_DW01_sub_1 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] DIFF;
   output CO;

   // Internal wires
   wire [9:0] carry;
endmodule

module SAO_1_DW01_sub_2 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] DIFF;
   output CO;

   // Internal wires
   wire [9:0] carry;
endmodule

module SAO_1_DW01_sub_3 (
	A, 
	B, 
	CI, 
	DIFF, 
	CO);
   input [8:0] A;
   input [8:0] B;
   input CI;
   output [8:0] DIFF;
   output CO;

   // Internal wires
   wire [9:0] carry;
endmodule

module SAO_1 (
	clk, 
	reset, 
	in_en, 
	din, 
	sao_type, 
	sao_band_pos, 
	sao_eo_class, 
	sao_offset, 
	lcu_x, 
	lcu_y, 
	lcu_size, 
	busy, 
	finish);
   input clk;
   input reset;
   input in_en;
   input [7:0] din;
   input [1:0] sao_type;
   input [4:0] sao_band_pos;
   input sao_eo_class;
   input [15:0] sao_offset;
   input [2:0] lcu_x;
   input [2:0] lcu_y;
   input [1:0] lcu_size;
   output busy;
   output finish;

   // Internal wires
   wire FE_UNCONNECTED_23;
   wire FE_UNCONNECTED_22;
   wire clk__L2_N0;
   wire clk__L1_N0;
   wire FE_UNCONNECTED_21;
   wire FE_OFN5_n733;
   wire FE_OFN4_n190;
   wire FE_OFN3_finish;
   wire FE_OFN2_finish;
   wire FE_OFN1_busy;
   wire FE_OFN0_busy;
   wire FE_UNCONNECTED_20;
   wire FE_UNCONNECTED_19;
   wire FE_UNCONNECTED_18;
   wire FE_UNCONNECTED_17;
   wire FE_UNCONNECTED_16;
   wire FE_UNCONNECTED_15;
   wire FE_UNCONNECTED_14;
   wire FE_UNCONNECTED_13;
   wire FE_UNCONNECTED_12;
   wire FE_UNCONNECTED_11;
   wire FE_UNCONNECTED_10;
   wire FE_UNCONNECTED_9;
   wire FE_UNCONNECTED_8;
   wire FE_UNCONNECTED_7;
   wire FE_UNCONNECTED_6;
   wire FE_UNCONNECTED_5;
   wire FE_UNCONNECTED_4;
   wire FE_UNCONNECTED_3;
   wire FE_UNCONNECTED_2;
   wire FE_UNCONNECTED_1;
   wire FE_UNCONNECTED_0;
   wire eo_ready;
   wire N183;
   wire N184;
   wire N185;
   wire N186;
   wire N187;
   wire N188;
   wire N189;
   wire busy_d;
   wire N240;
   wire N241;
   wire N242;
   wire N243;
   wire N245;
   wire N246;
   wire N247;
   wire N248;
   wire N249;
   wire N250;
   wire sao_off;
   wire N301;
   wire sao_bo;
   wire N302;
   wire N303;
   wire N311;
   wire N312;
   wire N313;
   wire N314;
   wire N315;
   wire N316;
   wire N317;
   wire N318;
   wire N319;
   wire N320;
   wire N321;
   wire N322;
   wire N339;
   wire N340;
   wire N341;
   wire N346;
   wire N347;
   wire N348;
   wire N382;
   wire N383;
   wire N384;
   wire N385;
   wire N386;
   wire N387;
   wire N388;
   wire N389;
   wire N390;
   wire N391;
   wire N392;
   wire N393;
   wire N396;
   wire N397;
   wire N398;
   wire N399;
   wire N400;
   wire N401;
   wire N402;
   wire N403;
   wire N404;
   wire N405;
   wire N406;
   wire N407;
   wire N408;
   wire N413;
   wire N414;
   wire N415;
   wire N416;
   wire N417;
   wire N418;
   wire N419;
   wire N420;
   wire N421;
   wire N422;
   wire N423;
   wire N425;
   wire N426;
   wire N427;
   wire N428;
   wire N429;
   wire N430;
   wire N431;
   wire N432;
   wire N433;
   wire N434;
   wire N435;
   wire N436;
   wire N437;
   wire N438;
   wire n97;
   wire n100;
   wire n101;
   wire n108;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n185;
   wire n186;
   wire n187;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n250;
   wire n252;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n290;
   wire n293;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n315;
   wire n316;
   wire n318;
   wire n319;
   wire n320;
   wire n324;
   wire n325;
   wire n361;
   wire n362;
   wire n363;
   wire n366;
   wire n367;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n447;
   wire n448;
   wire n449;
   wire n450;
   wire n451;
   wire n452;
   wire n453;
   wire n454;
   wire n455;
   wire n456;
   wire n457;
   wire n471;
   wire n472;
   wire n473;
   wire n474;
   wire n475;
   wire n476;
   wire n477;
   wire n478;
   wire n479;
   wire n480;
   wire n481;
   wire n482;
   wire n483;
   wire n484;
   wire n485;
   wire n487;
   wire n488;
   wire n489;
   wire n490;
   wire n491;
   wire n492;
   wire n493;
   wire n494;
   wire n495;
   wire n496;
   wire n497;
   wire n498;
   wire n499;
   wire n500;
   wire n518;
   wire n519;
   wire n520;
   wire n521;
   wire n522;
   wire n523;
   wire n524;
   wire n525;
   wire n526;
   wire n555;
   wire \add_583/carry[3] ;
   wire \add_583/carry[4] ;
   wire \add_583/carry[5] ;
   wire \add_583/carry[6] ;
   wire \add_583/carry[7] ;
   wire \add_583/carry[8] ;
   wire \add_583/carry[9] ;
   wire \add_583/carry[10] ;
   wire \add_583/carry[11] ;
   wire \add_583/carry[12] ;
   wire \add_583/carry[13] ;
   wire \add_581/carry[2] ;
   wire \add_581/carry[3] ;
   wire \add_581/carry[4] ;
   wire \add_581/carry[5] ;
   wire \add_581/carry[6] ;
   wire \add_581/carry[7] ;
   wire \add_581/carry[8] ;
   wire \add_581/carry[9] ;
   wire \add_581/carry[10] ;
   wire \add_581/carry[11] ;
   wire \add_581/carry[12] ;
   wire \add_581/carry[13] ;
   wire \add_579/carry[2] ;
   wire \add_579/carry[3] ;
   wire \add_579/carry[4] ;
   wire \add_579/carry[5] ;
   wire \add_579/carry[6] ;
   wire \add_579/carry[7] ;
   wire \add_579/carry[8] ;
   wire \add_579/carry[9] ;
   wire \add_579/carry[10] ;
   wire \add_579/carry[11] ;
   wire \add_579/carry[12] ;
   wire \add_579/carry[13] ;
   wire n556;
   wire n558;
   wire n559;
   wire n560;
   wire n561;
   wire n567;
   wire n568;
   wire n569;
   wire n570;
   wire n571;
   wire n572;
   wire n573;
   wire n575;
   wire n576;
   wire n733;
   wire n734;
   wire n735;
   wire n736;
   wire n737;
   wire n738;
   wire n739;
   wire n740;
   wire n741;
   wire n742;
   wire n743;
   wire n745;
   wire n746;
   wire [13:0] sao_counter;
   wire [4:0] sao_band_pos_syn;
   wire [15:0] sao_offset_syn;
   wire [4:0] din_shift;
   wire [2:0] buffer_0;
   wire [3:0] bo_offset;
   wire [8:0] din_bo_ori;
   wire [8:0] ver_sub1;
   wire [8:0] ver_sub2;
   wire [8:0] hor_sub1;
   wire [8:0] hor_sub2;
   wire [3:0] ver_offset;
   wire [3:0] hor_offset;
   wire [8:0] din_ver_ori;
   wire [8:0] din_hor_ori;
   wire [13:0] pixel_num;
   wire [7:0] buffer_next_2;
   wire [7:0] buffer_next_3;
   wire [7:0] buffer_next_4;
   wire [7:0] buffer_next_5;
   wire [7:0] buffer_next_6;
   wire [7:0] buffer_next_7;
   wire [7:0] buffer_next_8;
   wire [7:0] buffer_next_9;
   wire [7:0] buffer_next_10;
   wire [7:0] buffer_next_11;
   wire [7:0] buffer_next_12;
   wire [7:0] buffer_next_13;
   wire [7:0] buffer_next_14;
   wire [7:0] buffer_next_15;
   wire [7:0] buffer_next_16;
   wire [7:0] buffer_next_17;
   wire [7:0] buffer_next_18;
   wire [7:0] buffer_next_19;
   wire [7:0] buffer_next_20;
   wire [7:0] buffer_next_21;
   wire [7:0] buffer_next_22;
   wire [7:0] buffer_next_23;
   wire [7:0] buffer_next_24;
   wire [7:0] buffer_next_25;
   wire [7:0] buffer_next_26;
   wire [7:0] buffer_next_27;
   wire [7:0] buffer_next_28;
   wire [7:0] buffer_next_29;
   wire [7:0] buffer_next_30;
   wire [7:0] buffer_next_31;
   wire [7:0] buffer_next_32;
   wire [7:0] buffer_next_33;
   wire [7:0] buffer_next_34;
   wire [7:0] buffer_next_35;
   wire [7:0] buffer_next_36;
   wire [7:0] buffer_next_37;
   wire [7:0] buffer_next_38;
   wire [7:0] buffer_next_39;
   wire [7:0] buffer_next_40;
   wire [7:0] buffer_next_41;
   wire [7:0] buffer_next_42;
   wire [7:0] buffer_next_43;
   wire [7:0] buffer_next_44;
   wire [7:0] buffer_next_45;
   wire [7:0] buffer_next_46;
   wire [7:0] buffer_next_47;
   wire [7:0] buffer_next_48;
   wire [7:0] buffer_next_49;
   wire [7:0] buffer_next_50;
   wire [7:0] buffer_next_51;
   wire [7:0] buffer_next_52;
   wire [7:0] buffer_next_53;
   wire [7:0] buffer_next_54;
   wire [7:0] buffer_next_55;
   wire [7:0] buffer_next_56;
   wire [7:0] buffer_next_57;
   wire [7:0] buffer_next_58;
   wire [7:0] buffer_next_59;
   wire [7:0] buffer_next_60;
   wire [7:0] buffer_next_61;
   wire [7:0] buffer_next_62;
   wire [7:0] buffer_next_63;
   wire [7:0] buffer_next_64;
   wire [7:0] buffer_next_65;
   wire [7:0] buffer_next_66;
   wire [7:0] buffer_next_67;
   wire [7:0] buffer_next_68;
   wire [7:0] buffer_next_69;
   wire [7:0] buffer_next_70;
   wire [7:0] buffer_next_71;
   wire [7:0] buffer_next_72;
   wire [7:0] buffer_next_73;
   wire [7:0] buffer_next_74;
   wire [7:0] buffer_next_75;
   wire [7:0] buffer_next_76;
   wire [7:0] buffer_next_77;
   wire [7:0] buffer_next_78;
   wire [7:0] buffer_next_79;
   wire [7:0] buffer_next_80;
   wire [7:0] buffer_next_81;
   wire [7:0] buffer_next_82;
   wire [7:0] buffer_next_83;
   wire [7:0] buffer_next_84;
   wire [7:0] buffer_next_85;
   wire [7:0] buffer_next_86;
   wire [7:0] buffer_next_87;
   wire [7:0] buffer_next_88;
   wire [7:0] buffer_next_89;
   wire [7:0] buffer_next_90;
   wire [7:0] buffer_next_91;
   wire [7:0] buffer_next_92;
   wire [7:0] buffer_next_93;
   wire [7:0] buffer_next_94;
   wire [7:0] buffer_next_95;
   wire [7:0] buffer_next_96;
   wire [7:0] buffer_next_97;
   wire [7:0] buffer_next_98;
   wire [7:0] buffer_next_99;
   wire [7:0] buffer_next_100;
   wire [7:0] buffer_next_101;
   wire [7:0] buffer_next_102;
   wire [7:0] buffer_next_103;
   wire [7:0] buffer_next_104;
   wire [7:0] buffer_next_105;
   wire [7:0] buffer_next_106;
   wire [7:0] buffer_next_107;
   wire [7:0] buffer_next_108;
   wire [7:0] buffer_next_109;
   wire [7:0] buffer_next_110;
   wire [7:0] buffer_next_111;
   wire [7:0] buffer_next_112;
   wire [7:0] buffer_next_113;
   wire [7:0] buffer_next_114;
   wire [7:0] buffer_next_115;
   wire [7:0] buffer_next_116;
   wire [7:0] buffer_next_117;
   wire [7:0] buffer_next_118;
   wire [7:0] buffer_next_119;
   wire [7:0] buffer_next_120;
   wire [7:0] buffer_next_121;
   wire [7:0] buffer_next_122;
   wire [7:0] buffer_next_123;
   wire [7:0] buffer_next_124;
   wire [7:0] buffer_next_125;
   wire [7:0] buffer_next_126;
   wire [7:0] buffer_next_127;
   wire [7:0] buffer_next_128;
   wire [6:0] eo_counter;
   wire [5:0] busy_cnt;
   wire [7:0] sram_din;
   wire [5:2] \add_481/carry ;
   wire [8:1] \add_156/carry ;
   wire [5:1] \add_149/carry ;
   wire [5:2] \add_148/carry ;
   wire [8:1] \add_198_aco/carry ;
   wire [8:1] \add_197_aco/carry ;

   assign N339 = lcu_x[0] ;
   assign N340 = lcu_x[1] ;
   assign N341 = lcu_x[2] ;
   assign N346 = lcu_y[0] ;
   assign N347 = lcu_y[1] ;
   assign N348 = lcu_y[2] ;

   CLKINVX20 clk__L2_I0 (.Y(clk__L2_N0),
	.A(clk__L1_N0));
   CLKINVX20 clk__L1_I0 (.Y(clk__L1_N0),
	.A(clk));
   CLKBUFX3 FE_OFC5_n733 (.Y(FE_OFN5_n733),
	.A(n733));
   CLKBUFX2 FE_OFC4_n190 (.Y(FE_OFN4_n190),
	.A(n190));
   INVX16 FE_OFC3_finish (.Y(finish),
	.A(FE_OFN3_finish));
   INVX1 FE_OFC2_finish (.Y(FE_OFN3_finish),
	.A(FE_OFN2_finish));
   INVX16 FE_OFC1_busy (.Y(busy),
	.A(FE_OFN1_busy));
   INVX1 FE_OFC0_busy (.Y(FE_OFN1_busy),
	.A(FE_OFN0_busy));
   sram_16384x8 golden_sram (.A(pixel_num),
	.D(sram_din),
	.CLK(clk),
	.CEN(FE_UNCONNECTED_0),
	.WEN(FE_UNCONNECTED_1));
   SAO_1_DW01_inc_0 add_585 (.A(pixel_num),
	.SUM({ N438,
		N437,
		N436,
		N435,
		N434,
		N433,
		N432,
		N431,
		N430,
		N429,
		N428,
		N427,
		N426,
		N425 }));
   SAO_1_DW01_inc_1 add_563 (.A(sao_counter),
	.SUM({ FE_UNCONNECTED_3,
		FE_UNCONNECTED_2,
		N322,
		N321,
		N320,
		N319,
		N318,
		N317,
		N316,
		N315,
		N314,
		N313,
		N312,
		N311 }));
   SAO_1_DW01_inc_3 add_425 (.A(eo_counter),
	.SUM({ N189,
		N188,
		N187,
		N186,
		N185,
		N184,
		N183 }));
   SAO_1_DW01_sub_0 sub_162 (.A({ 1'b0,
		FE_UNCONNECTED_12,
		FE_UNCONNECTED_13,
		FE_UNCONNECTED_14,
		FE_UNCONNECTED_15,
		FE_UNCONNECTED_16,
		FE_UNCONNECTED_17,
		FE_UNCONNECTED_18,
		FE_UNCONNECTED_19 }),
	.B({ 1'b0,
		FE_UNCONNECTED_4,
		FE_UNCONNECTED_5,
		FE_UNCONNECTED_6,
		FE_UNCONNECTED_7,
		FE_UNCONNECTED_8,
		FE_UNCONNECTED_9,
		FE_UNCONNECTED_10,
		FE_UNCONNECTED_11 }),
	.CI(1'b0),
	.DIFF(ver_sub1));
   SAO_1_DW01_sub_1 sub_163 (.A({ 1'b0,
		FE_UNCONNECTED_12,
		FE_UNCONNECTED_13,
		FE_UNCONNECTED_14,
		FE_UNCONNECTED_15,
		FE_UNCONNECTED_16,
		FE_UNCONNECTED_17,
		FE_UNCONNECTED_18,
		FE_UNCONNECTED_19 }),
	.B({ 1'b0,
		din_shift,
		buffer_0 }),
	.CI(1'b0),
	.DIFF(ver_sub2));
   SAO_1_DW01_sub_2 sub_165 (.A({ 1'b0,
		buffer_next_3 }),
	.B({ 1'b0,
		buffer_next_4 }),
	.CI(1'b0),
	.DIFF(hor_sub1));
   SAO_1_DW01_sub_3 sub_166 (.A({ 1'b0,
		buffer_next_3 }),
	.B({ 1'b0,
		buffer_next_2 }),
	.CI(1'b0),
	.DIFF(hor_sub2));
   DFFRX1 finish_reg (.RN(FE_OFN5_n733),
	.Q(FE_OFN2_finish),
	.D(n471),
	.CK(clk__L2_N0));
   DFFRX1 eo_ready_d_reg (.RN(n733),
	.QN(n455),
	.D(eo_ready),
	.CK(clk__L2_N0));
   DFFRX1 busy_d_reg (.RN(n733),
	.Q(busy_d),
	.D(busy),
	.CK(clk__L2_N0));
   DFFRX1 \busy_cnt_reg[1]  (.RN(FE_OFN5_n733),
	.QN(n429),
	.Q(busy_cnt[1]),
	.D(N246),
	.CK(clk__L2_N0));
   DFFRX1 \busy_cnt_reg[3]  (.RN(FE_OFN5_n733),
	.QN(n426),
	.Q(busy_cnt[3]),
	.D(N248),
	.CK(clk__L2_N0));
   DFFRX1 \busy_cnt_reg[5]  (.RN(FE_OFN5_n733),
	.QN(n366),
	.Q(busy_cnt[5]),
	.D(N250),
	.CK(clk__L2_N0));
   DFFRX1 eo_type_reg (.RN(n733),
	.QN(n425),
	.D(n488),
	.CK(clk__L2_N0));
   DFFRX1 \busy_cnt_reg[4]  (.RN(n733),
	.QN(n367),
	.Q(busy_cnt[4]),
	.D(N249),
	.CK(clk__L2_N0));
   DFFRX1 sao_bo_reg (.RN(n733),
	.Q(sao_bo),
	.D(N302),
	.CK(clk__L2_N0));
   DFFRX1 eo_ready_reg (.RN(n733),
	.QN(n457),
	.Q(eo_ready),
	.D(n524),
	.CK(clk__L2_N0));
   DFFRX1 \eo_counter_reg[3]  (.RN(n733),
	.QN(n449),
	.Q(eo_counter[3]),
	.D(n521),
	.CK(clk__L2_N0));
   DFFRX1 \eo_counter_reg[0]  (.RN(n733),
	.QN(n453),
	.Q(eo_counter[0]),
	.D(n523),
	.CK(clk__L2_N0));
   DFFRX1 \eo_counter_reg[2]  (.RN(n733),
	.QN(n448),
	.Q(eo_counter[2]),
	.D(n522),
	.CK(clk__L2_N0));
   DFFRX1 \busy_cnt_reg[0]  (.RN(FE_OFN5_n733),
	.Q(busy_cnt[0]),
	.D(N245),
	.CK(clk__L2_N0));
   DFFRX1 sao_eo_reg (.RN(n733),
	.QN(n573),
	.Q(n454),
	.D(N303),
	.CK(clk__L2_N0));
   DFFRX1 \busy_cnt_reg[2]  (.RN(n733),
	.QN(n428),
	.Q(busy_cnt[2]),
	.D(N247),
	.CK(clk__L2_N0));
   DFFRX1 sao_off_reg (.RN(n733),
	.QN(n570),
	.Q(sao_off),
	.D(N301),
	.CK(clk__L2_N0));
   DFFRX1 \eo_counter_reg[1]  (.RN(n733),
	.QN(n456),
	.Q(eo_counter[1]),
	.D(n525),
	.CK(clk__L2_N0));
   DFFRX1 \eo_counter_reg[6]  (.RN(n733),
	.QN(n447),
	.Q(eo_counter[6]),
	.D(n518),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[13]  (.RN(FE_OFN5_n733),
	.Q(pixel_num[13]),
	.D(n484),
	.CK(clk__L2_N0));
   DFFRX1 \eo_counter_reg[4]  (.RN(n733),
	.QN(n452),
	.Q(eo_counter[4]),
	.D(n520),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[12]  (.RN(FE_OFN5_n733),
	.Q(pixel_num[12]),
	.D(n483),
	.CK(clk__L2_N0));
   DFFRX1 \eo_counter_reg[5]  (.RN(n733),
	.QN(n451),
	.Q(eo_counter[5]),
	.D(n519),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[8]  (.RN(FE_OFN5_n733),
	.QN(n559),
	.Q(sao_counter[8]),
	.D(n493),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[9]  (.RN(FE_OFN5_n733),
	.QN(n568),
	.Q(sao_counter[9]),
	.D(n492),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[10]  (.RN(FE_OFN5_n733),
	.Q(sao_counter[10]),
	.D(n491),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[11]  (.RN(FE_OFN5_n733),
	.Q(sao_counter[11]),
	.D(n490),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[0]  (.RN(FE_OFN5_n733),
	.Q(sao_counter[0]),
	.D(n526),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[7]  (.RN(FE_OFN5_n733),
	.Q(sao_counter[7]),
	.D(n494),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[4]  (.RN(FE_OFN5_n733),
	.QN(n567),
	.Q(sao_counter[4]),
	.D(n497),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[2]  (.RN(FE_OFN5_n733),
	.Q(sao_counter[2]),
	.D(n499),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[6]  (.RN(FE_OFN5_n733),
	.Q(pixel_num[6]),
	.D(n476),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[3]  (.RN(FE_OFN5_n733),
	.Q(sao_counter[3]),
	.D(n498),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[9]  (.RN(FE_OFN5_n733),
	.Q(pixel_num[9]),
	.D(n473),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[8]  (.RN(FE_OFN5_n733),
	.Q(pixel_num[8]),
	.D(n474),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[10]  (.RN(FE_OFN5_n733),
	.Q(pixel_num[10]),
	.D(n472),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[0]  (.RN(FE_OFN5_n733),
	.QN(n571),
	.Q(pixel_num[0]),
	.D(n485),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[2]  (.RN(n733),
	.QN(n561),
	.Q(pixel_num[2]),
	.D(n480),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[3]  (.RN(n733),
	.QN(n572),
	.Q(pixel_num[3]),
	.D(n479),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[5]  (.RN(FE_OFN5_n733),
	.Q(pixel_num[5]),
	.D(n477),
	.CK(clk__L2_N0));
   DFFRX1 busy_reg (.RN(FE_OFN5_n733),
	.QN(n450),
	.Q(FE_OFN0_busy),
	.D(n489),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[11]  (.RN(FE_OFN5_n733),
	.QN(n569),
	.Q(pixel_num[11]),
	.D(n482),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[6]  (.RN(FE_OFN5_n733),
	.Q(sao_counter[6]),
	.D(n495),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[7]  (.RN(FE_OFN5_n733),
	.Q(pixel_num[7]),
	.D(n475),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[1]  (.RN(FE_OFN5_n733),
	.Q(sao_counter[1]),
	.D(n500),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[1]  (.RN(FE_OFN5_n733),
	.Q(pixel_num[1]),
	.D(n481),
	.CK(clk__L2_N0));
   DFFRX1 \pixel_num_reg[4]  (.RN(FE_OFN5_n733),
	.QN(n560),
	.Q(pixel_num[4]),
	.D(n478),
	.CK(clk__L2_N0));
   DFFRX1 eo_class_reg (.RN(n733),
	.QN(n427),
	.Q(n556),
	.D(n487),
	.CK(clk__L2_N0));
   DFFRX1 \sao_counter_reg[5]  (.RN(FE_OFN5_n733),
	.QN(n558),
	.Q(sao_counter[5]),
	.D(n496),
	.CK(clk__L2_N0));
   NOR4X1 U413 (.Y(n363),
	.D(sao_counter[3]),
	.C(sao_counter[2]),
	.B(sao_counter[1]),
	.A(sao_counter[0]));
   NOR3X1 U414 (.Y(n189),
	.C(n250),
	.B(sao_counter[5]),
	.A(n247));
   INVX3 U416 (.Y(n733),
	.A(reset));
   NOR2BX1 U531 (.Y(n182),
	.B(n248),
	.AN(n246));
   NOR2BX2 U533 (.Y(n187),
	.B(n244),
	.AN(n243));
   NOR2BX1 U534 (.Y(n246),
	.B(n742),
	.AN(n243));
   NOR4BBX1 U536 (.Y(n190),
	.D(n183),
	.C(n182),
	.BN(n243),
	.AN(n245));
   NOR2X1 U537 (.Y(n245),
	.B(n186),
	.A(n742));
   CLKINVX1 U538 (.Y(n735),
	.A(n100));
   AND4X1 U539 (.Y(n183),
	.D(n743),
	.C(n248),
	.B(n247),
	.A(n246));
   CLKINVX1 U540 (.Y(n742),
	.A(n244));
   NOR2BX1 U542 (.Y(n186),
	.B(n247),
	.AN(n246));
   NAND3X1 U601 (.Y(n247),
	.C(n739),
	.B(n567),
	.A(n363));
   NAND4X1 U602 (.Y(n248),
	.D(n558),
	.C(n567),
	.B(n363),
	.A(n108));
   NAND3X1 U603 (.Y(n250),
	.C(n362),
	.B(n568),
	.A(n559));
   NAND4X1 U604 (.Y(n100),
	.D(n558),
	.C(n567),
	.B(n742),
	.A(n362));
   NOR2X1 U605 (.Y(n243),
	.B(n735),
	.A(n97));
   NAND2X1 U606 (.Y(n244),
	.B(n361),
	.A(n363));
   OAI2BB2XL U607 (.Y(n492),
	.B1(n568),
	.B0(n743),
	.A1N(n743),
	.A0N(N320));
   NAND3X1 U608 (.Y(n479),
	.C(n213),
	.B(n212),
	.A(n211));
   NAND2X1 U609 (.Y(n212),
	.B(n187),
	.A(N383));
   AOI221XL U610 (.Y(n213),
	.C0(n214),
	.B1(n183),
	.B0(N428),
	.A1(n182),
	.A0(N413));
   NAND2X1 U611 (.Y(n211),
	.B(FE_OFN4_n190),
	.A(pixel_num[3]));
   NAND3X1 U612 (.Y(n480),
	.C(n217),
	.B(n216),
	.A(n215));
   NAND2X1 U613 (.Y(n216),
	.B(n187),
	.A(N382));
   AOI221XL U614 (.Y(n217),
	.C0(n218),
	.B1(n183),
	.B0(N427),
	.A1(n182),
	.A0(N397));
   NAND2X1 U615 (.Y(n215),
	.B(FE_OFN4_n190),
	.A(pixel_num[2]));
   NAND3X1 U616 (.Y(n485),
	.C(n241),
	.B(n240),
	.A(n239));
   NAND2X1 U617 (.Y(n240),
	.B(n187),
	.A(n571));
   AOI221XL U618 (.Y(n241),
	.C0(n242),
	.B1(n183),
	.B0(N425),
	.A1(n182),
	.A0(n571));
   NAND2X1 U619 (.Y(n239),
	.B(pixel_num[0]),
	.A(FE_OFN4_n190));
   AND2X2 U620 (.Y(n214),
	.B(n186),
	.A(N398));
   AND2X2 U621 (.Y(n218),
	.B(n186),
	.A(N397));
   AND2X2 U622 (.Y(n242),
	.B(n186),
	.A(n571));
   NOR2BX1 U623 (.Y(n297),
	.B(eo_ready),
	.AN(n300));
   CLKINVX1 U624 (.Y(n743),
	.A(n555));
   OAI2BB2XL U626 (.Y(n493),
	.B1(n559),
	.B0(n743),
	.A1N(n743),
	.A0N(N319));
   OAI2BB2XL U627 (.Y(n496),
	.B1(n558),
	.B0(n743),
	.A1N(n743),
	.A0N(N316));
   OAI2BB2XL U628 (.Y(n497),
	.B1(n567),
	.B0(n743),
	.A1N(n743),
	.A0N(N315));
   CLKINVX1 U633 (.Y(n746),
	.A(n288));
   CLKINVX1 U634 (.Y(n741),
	.A(n361));
   CLKINVX1 U635 (.Y(n738),
	.A(n108));
   CLKINVX1 U636 (.Y(n739),
	.A(n252));
   NAND3X1 U766 (.Y(n472),
	.C(n237),
	.B(n236),
	.A(n235));
   NAND2X1 U767 (.Y(n235),
	.B(FE_OFN4_n190),
	.A(pixel_num[10]));
   NAND2X1 U768 (.Y(n236),
	.B(n187),
	.A(N390));
   AOI221XL U769 (.Y(n237),
	.C0(n238),
	.B1(n183),
	.B0(N435),
	.A1(n182),
	.A0(N420));
   NAND3X1 U770 (.Y(n482),
	.C(n233),
	.B(n232),
	.A(n231));
   NAND2X1 U771 (.Y(n231),
	.B(FE_OFN4_n190),
	.A(pixel_num[11]));
   AOI22X1 U772 (.Y(n232),
	.B1(n735),
	.B0(N346),
	.A1(n187),
	.A0(N391));
   AOI221XL U773 (.Y(n233),
	.C0(n234),
	.B1(n183),
	.B0(N436),
	.A1(n182),
	.A0(N421));
   NAND3X1 U774 (.Y(n483),
	.C(n229),
	.B(n228),
	.A(n227));
   AOI22X1 U775 (.Y(n227),
	.B1(FE_OFN4_n190),
	.B0(pixel_num[12]),
	.A1(n189),
	.A0(N346));
   AOI22X1 U776 (.Y(n228),
	.B1(n735),
	.B0(N347),
	.A1(n187),
	.A0(N392));
   AOI221XL U777 (.Y(n229),
	.C0(n230),
	.B1(n183),
	.B0(N437),
	.A1(n182),
	.A0(N422));
   NAND3X1 U780 (.Y(n484),
	.C(n225),
	.B(n224),
	.A(n223));
   AOI22X1 U781 (.Y(n223),
	.B1(pixel_num[13]),
	.B0(FE_OFN4_n190),
	.A1(n189),
	.A0(N347));
   AOI22X1 U782 (.Y(n224),
	.B1(n735),
	.B0(N348),
	.A1(n187),
	.A0(N393));
   AOI221XL U783 (.Y(n225),
	.C0(n226),
	.B1(n183),
	.B0(N438),
	.A1(n182),
	.A0(N423));
   NAND3X1 U784 (.Y(n473),
	.C(n181),
	.B(n180),
	.A(n179));
   NAND2X1 U785 (.Y(n179),
	.B(FE_OFN4_n190),
	.A(pixel_num[9]));
   NAND2X1 U786 (.Y(n180),
	.B(n187),
	.A(N389));
   AOI221XL U787 (.Y(n181),
	.C0(n575),
	.B1(n183),
	.B0(N434),
	.A1(n182),
	.A0(N419));
   AO22X1 U788 (.Y(n226),
	.B1(n186),
	.B0(N408),
	.A1(n185),
	.A0(N346));
   AND2X2 U789 (.Y(n575),
	.B(n186),
	.A(N404));
   AND2X2 U790 (.Y(n238),
	.B(n186),
	.A(N405));
   AND2X2 U791 (.Y(n234),
	.B(n186),
	.A(N406));
   AND2X2 U792 (.Y(n230),
	.B(n186),
	.A(N407));
   OAI21XL U793 (.Y(n296),
	.B0(n299),
	.A1(n573),
	.A0(n243));
   NOR4X1 U794 (.Y(n185),
	.D(sao_counter[11]),
	.C(sao_counter[10]),
	.B(n250),
	.A(n248));
   AO22X1 U795 (.Y(n198),
	.B1(n186),
	.B0(N402),
	.A1(n185),
	.A0(N340));
   NOR3X1 U797 (.Y(n362),
	.C(n736),
	.B(sao_counter[7]),
	.A(sao_counter[6]));
   NAND4BX1 U798 (.Y(n313),
	.D(n427),
	.C(sao_counter[6]),
	.B(sao_counter[5]),
	.AN(sao_counter[1]));
   NAND3X1 U799 (.Y(n310),
	.C(sao_counter[1]),
	.B(n556),
	.A(sao_counter[6]));
   OAI2BB2XL U800 (.Y(n518),
	.B1(n447),
	.B0(n296),
	.A1N(n297),
	.A0N(N189));
   OAI2BB2XL U801 (.Y(n519),
	.B1(n451),
	.B0(n296),
	.A1N(n297),
	.A0N(N188));
   OAI2BB2XL U802 (.Y(n520),
	.B1(n452),
	.B0(n296),
	.A1N(n297),
	.A0N(N187));
   OAI2BB2XL U803 (.Y(n521),
	.B1(n449),
	.B0(n296),
	.A1N(n297),
	.A0N(N186));
   OAI2BB2XL U804 (.Y(n522),
	.B1(n448),
	.B0(n296),
	.A1N(n297),
	.A0N(N185));
   OAI2BB2XL U805 (.Y(n525),
	.B1(n456),
	.B0(n296),
	.A1N(n297),
	.A0N(N184));
   OAI21XL U806 (.Y(n523),
	.B0(n298),
	.A1(n296),
	.A0(n453));
   AOI22X1 U807 (.Y(n298),
	.B1(n296),
	.B0(n299),
	.A1(n297),
	.A0(N183));
   OAI21XL U808 (.Y(n489),
	.B0(n306),
	.A1(n305),
	.A0(n450));
   AOI221XL U809 (.Y(n305),
	.C0(n318),
	.B1(n556),
	.B0(n426),
	.A1(busy_cnt[1]),
	.A0(n427));
   NAND4X1 U810 (.Y(n306),
	.D(n307),
	.C(sao_counter[2]),
	.B(sao_counter[7]),
	.A(sao_counter[3]));
   OAI31XL U811 (.Y(n97),
	.B0(n734),
	.A2(n247),
	.A1(sao_counter[5]),
	.A0(n250));
   CLKINVX1 U812 (.Y(n734),
	.A(n185));
   AOI211X1 U814 (.Y(n307),
	.C0(n425),
	.B0(sao_counter[0]),
	.A1(n309),
	.A0(n308));
   OR4X1 U815 (.Y(n309),
	.D(sao_counter[4]),
	.C(n741),
	.B(n558),
	.A(n310));
   NAND2X1 U816 (.Y(n308),
	.B(n311),
	.A(sao_counter[4]));
   OAI32X1 U817 (.Y(n311),
	.B1(n313),
	.B0(n741),
	.A2(n568),
	.A1(n312),
	.A0(n559));
   NAND3X1 U818 (.Y(n475),
	.C(n197),
	.B(n196),
	.A(n195));
   NAND2X1 U819 (.Y(n196),
	.B(n187),
	.A(N387));
   AOI221XL U820 (.Y(n197),
	.C0(n198),
	.B1(n183),
	.B0(N432),
	.A1(n182),
	.A0(N417));
   AOI22X1 U821 (.Y(n195),
	.B1(pixel_num[7]),
	.B0(FE_OFN4_n190),
	.A1(n189),
	.A0(N341));
   NAND3X1 U822 (.Y(n476),
	.C(n201),
	.B(n200),
	.A(n199));
   AOI22X1 U823 (.Y(n200),
	.B1(n735),
	.B0(N341),
	.A1(n187),
	.A0(N386));
   AOI221XL U824 (.Y(n201),
	.C0(n202),
	.B1(n183),
	.B0(N431),
	.A1(n182),
	.A0(N416));
   AOI22X1 U825 (.Y(n199),
	.B1(pixel_num[6]),
	.B0(FE_OFN4_n190),
	.A1(n189),
	.A0(N340));
   NAND3X1 U826 (.Y(n477),
	.C(n205),
	.B(n204),
	.A(n203));
   AOI22X1 U827 (.Y(n204),
	.B1(n735),
	.B0(N340),
	.A1(n187),
	.A0(N385));
   AOI221XL U828 (.Y(n205),
	.C0(n206),
	.B1(n183),
	.B0(N430),
	.A1(n182),
	.A0(N415));
   AOI22X1 U829 (.Y(n203),
	.B1(FE_OFN4_n190),
	.B0(pixel_num[5]),
	.A1(n189),
	.A0(N339));
   NAND3X1 U830 (.Y(n478),
	.C(n209),
	.B(n208),
	.A(n207));
   AOI22X1 U831 (.Y(n208),
	.B1(n735),
	.B0(N339),
	.A1(n187),
	.A0(N384));
   AOI221XL U832 (.Y(n209),
	.C0(n210),
	.B1(n183),
	.B0(N429),
	.A1(n182),
	.A0(N414));
   NAND2X1 U833 (.Y(n207),
	.B(FE_OFN4_n190),
	.A(pixel_num[4]));
   NAND3X1 U834 (.Y(n474),
	.C(n193),
	.B(n192),
	.A(n191));
   NAND2X1 U835 (.Y(n191),
	.B(FE_OFN4_n190),
	.A(pixel_num[8]));
   NAND2X1 U836 (.Y(n192),
	.B(n187),
	.A(N388));
   AOI221XL U837 (.Y(n193),
	.C0(n194),
	.B1(n183),
	.B0(N433),
	.A1(n182),
	.A0(N418));
   NAND3X1 U838 (.Y(n481),
	.C(n221),
	.B(n220),
	.A(n219));
   NAND2X1 U839 (.Y(n220),
	.B(n187),
	.A(N396));
   AOI221XL U840 (.Y(n221),
	.C0(n222),
	.B1(n183),
	.B0(N426),
	.A1(n182),
	.A0(N396));
   NAND2X1 U841 (.Y(n219),
	.B(FE_OFN4_n190),
	.A(pixel_num[1]));
   AO22X1 U842 (.Y(n490),
	.B1(n743),
	.B0(N322),
	.A1(sao_counter[11]),
	.A0(n555));
   AO22X1 U843 (.Y(n491),
	.B1(n743),
	.B0(N321),
	.A1(sao_counter[10]),
	.A0(n555));
   AO22X1 U844 (.Y(n202),
	.B1(n186),
	.B0(N401),
	.A1(n185),
	.A0(N339));
   AO22X1 U845 (.Y(n194),
	.B1(n186),
	.B0(N403),
	.A1(n185),
	.A0(N341));
   AOI32X1 U846 (.Y(n312),
	.B1(n315),
	.B0(n739),
	.A2(n314),
	.A1(sao_counter[11]),
	.A0(sao_counter[10]));
   OAI21XL U847 (.Y(n315),
	.B0(n313),
	.A1(n310),
	.A0(sao_counter[5]));
   AOI21X1 U848 (.Y(n314),
	.B0(n738),
	.A1(n313),
	.A0(n316));
   NAND4BX1 U849 (.Y(n316),
	.D(n556),
	.C(sao_counter[5]),
	.B(sao_counter[1]),
	.AN(sao_counter[6]));
   AND2X2 U850 (.Y(n210),
	.B(n186),
	.A(N399));
   AND2X2 U851 (.Y(n222),
	.B(n186),
	.A(N396));
   AND2X2 U852 (.Y(n206),
	.B(n186),
	.A(N400));
   NOR3X1 U853 (.Y(n555),
	.C(eo_ready),
	.B(sao_off),
	.A(sao_bo));
   OAI22XL U855 (.Y(n299),
	.B1(n300),
	.B0(eo_ready),
	.A1(n457),
	.A0(n455));
   NAND4X1 U857 (.Y(n300),
	.D(n304),
	.C(n447),
	.B(n452),
	.A(n451));
   NOR3X1 U858 (.Y(n304),
	.C(eo_counter[1]),
	.B(n285),
	.A(eo_counter[0]));
   NOR4X1 U859 (.Y(n471),
	.D(finish),
	.C(n571),
	.B(n275),
	.A(n274));
   NAND3X1 U860 (.Y(n275),
	.C(pixel_num[13]),
	.B(pixel_num[7]),
	.A(pixel_num[6]));
   NAND3X1 U861 (.Y(n274),
	.C(n276),
	.B(pixel_num[4]),
	.A(n101));
   AND3X2 U862 (.Y(n276),
	.C(pixel_num[5]),
	.B(pixel_num[12]),
	.A(pixel_num[11]));
   NAND2X1 U867 (.Y(n279),
	.B(n300),
	.A(n454));
   NAND2X1 U868 (.Y(n288),
	.B(busy_d),
	.A(n450));
   NAND3X1 U888 (.Y(n281),
	.C(n447),
	.B(eo_counter[0]),
	.A(n293));
   XOR2X1 U889 (.Y(n293),
	.B(n456),
	.A(sao_eo_class));
   AOI32X1 U890 (.Y(n324),
	.B1(n325),
	.B0(n366),
	.A2(n108),
	.A1(busy_cnt[5]),
	.A0(busy_cnt[4]));
   OAI22XL U891 (.Y(n325),
	.B1(busy_cnt[4]),
	.B0(n741),
	.A1(n252),
	.A0(n367));
   AND4X1 U893 (.Y(n101),
	.D(n277),
	.C(pixel_num[2]),
	.B(pixel_num[10]),
	.A(pixel_num[1]));
   AND3X2 U894 (.Y(n277),
	.C(pixel_num[8]),
	.B(pixel_num[3]),
	.A(pixel_num[9]));
   NAND2X1 U895 (.Y(n285),
	.B(n449),
	.A(n448));
   NOR2X1 U896 (.Y(N250),
	.B(n450),
	.A(n576));
   XNOR2X1 U897 (.Y(n576),
	.B(busy_cnt[5]),
	.A(\add_481/carry [5]));
   NOR2BX1 U898 (.Y(N249),
	.B(n450),
	.AN(N243));
   NOR2BX1 U899 (.Y(N248),
	.B(n450),
	.AN(N242));
   NOR2BX1 U900 (.Y(N247),
	.B(n450),
	.AN(N241));
   ADDHXL U901 (.S(N240),
	.CO(\add_481/carry [2]),
	.B(busy_cnt[0]),
	.A(busy_cnt[1]));
   ADDHXL U902 (.S(N241),
	.CO(\add_481/carry [3]),
	.B(\add_481/carry [2]),
	.A(busy_cnt[2]));
   ADDHXL U903 (.S(N242),
	.CO(\add_481/carry [4]),
	.B(\add_481/carry [3]),
	.A(busy_cnt[3]));
   OAI211X1 U908 (.Y(n318),
	.C0(n320),
	.B0(busy_cnt[0]),
	.A1(n319),
	.A0(n426));
   OAI31XL U909 (.Y(n320),
	.B0(n429),
	.A2(busy_cnt[5]),
	.A1(busy_cnt[4]),
	.A0(busy_cnt[2]));
   NOR2X1 U910 (.Y(n319),
	.B(n428),
	.A(n324));
   AO22X1 U911 (.Y(n494),
	.B1(n743),
	.B0(N318),
	.A1(sao_counter[7]),
	.A0(n555));
   AO22X1 U912 (.Y(n495),
	.B1(n743),
	.B0(N317),
	.A1(sao_counter[6]),
	.A0(n555));
   AO22X1 U913 (.Y(n498),
	.B1(n743),
	.B0(N314),
	.A1(sao_counter[3]),
	.A0(n555));
   AO22X1 U914 (.Y(n499),
	.B1(n743),
	.B0(N313),
	.A1(sao_counter[2]),
	.A0(n555));
   AO22X1 U915 (.Y(n500),
	.B1(n743),
	.B0(N312),
	.A1(sao_counter[1]),
	.A0(n555));
   AO22X1 U916 (.Y(n526),
	.B1(n743),
	.B0(N311),
	.A1(sao_counter[0]),
	.A0(n555));
   OAI32X1 U917 (.Y(n524),
	.B1(n746),
	.B0(n457),
	.A2(n282),
	.A1(n281),
	.A0(n280));
   OAI2BB2XL U918 (.Y(n282),
	.B1(eo_counter[4]),
	.B0(n451),
	.A1N(n285),
	.A0N(n737));
   OAI221XL U919 (.Y(n280),
	.C0(n288),
	.B1(n287),
	.B0(n452),
	.A1(n737),
	.A0(n286));
   AOI21X1 U920 (.Y(n286),
	.B0(n290),
	.A1(n741),
	.A0(n452));
   OAI32X1 U921 (.Y(n487),
	.B1(n279),
	.B0(n737),
	.A2(n746),
	.A1(n427),
	.A0(n745));
   CLKINVX1 U922 (.Y(n745),
	.A(n279));
   OR2X1 U923 (.Y(n290),
	.B(n448),
	.A(n449));
   AOI221XL U924 (.Y(n287),
	.C0(n737),
	.B1(n252),
	.B0(n451),
	.A1(eo_counter[5]),
	.A0(n738));
   ADDHXL U925 (.S(N243),
	.CO(\add_481/carry [5]),
	.B(\add_481/carry [4]),
	.A(busy_cnt[4]));
   OAI21XL U934 (.Y(n488),
	.B0(n279),
	.A1(n746),
	.A0(n425));
   NOR2BX1 U935 (.Y(N246),
	.B(n450),
	.AN(N240));
   NOR2X1 U936 (.Y(N245),
	.B(n450),
	.A(busy_cnt[0]));
   NOR2X1 U937 (.Y(n108),
	.B(lcu_size[0]),
	.A(n740));
   NAND2X1 U938 (.Y(n252),
	.B(n740),
	.A(lcu_size[0]));
   NOR2X1 U939 (.Y(n361),
	.B(lcu_size[1]),
	.A(lcu_size[0]));
   NOR3BXL U940 (.Y(N303),
	.C(n736),
	.B(sao_type[0]),
	.AN(sao_type[1]));
   NOR3BXL U941 (.Y(N302),
	.C(n736),
	.B(sao_type[1]),
	.AN(sao_type[0]));
   NOR3X1 U942 (.Y(N301),
	.C(sao_type[0]),
	.B(sao_type[1]),
	.A(n736));
   CLKINVX1 U943 (.Y(n736),
	.A(in_en));
   CLKINVX1 U944 (.Y(n740),
	.A(lcu_size[1]));
   CLKINVX1 U945 (.Y(n737),
	.A(sao_eo_class));
   XOR2X1 U968 (.Y(N408),
	.B(\add_581/carry[13] ),
	.A(pixel_num[13]));
   AND2X1 U969 (.Y(\add_581/carry[13] ),
	.B(pixel_num[12]),
	.A(\add_581/carry[12] ));
   XOR2X1 U970 (.Y(N407),
	.B(\add_581/carry[12] ),
	.A(pixel_num[12]));
   AND2X1 U971 (.Y(\add_581/carry[12] ),
	.B(pixel_num[11]),
	.A(\add_581/carry[11] ));
   XOR2X1 U972 (.Y(N406),
	.B(\add_581/carry[11] ),
	.A(pixel_num[11]));
   AND2X1 U973 (.Y(\add_581/carry[11] ),
	.B(pixel_num[10]),
	.A(\add_581/carry[10] ));
   XOR2X1 U974 (.Y(N405),
	.B(\add_581/carry[10] ),
	.A(pixel_num[10]));
   AND2X1 U975 (.Y(\add_581/carry[10] ),
	.B(pixel_num[9]),
	.A(\add_581/carry[9] ));
   XOR2X1 U976 (.Y(N404),
	.B(\add_581/carry[9] ),
	.A(pixel_num[9]));
   AND2X1 U977 (.Y(\add_581/carry[9] ),
	.B(pixel_num[8]),
	.A(\add_581/carry[8] ));
   XOR2X1 U978 (.Y(N403),
	.B(\add_581/carry[8] ),
	.A(pixel_num[8]));
   AND2X1 U979 (.Y(\add_581/carry[8] ),
	.B(pixel_num[7]),
	.A(\add_581/carry[7] ));
   XOR2X1 U980 (.Y(N402),
	.B(\add_581/carry[7] ),
	.A(pixel_num[7]));
   OR2X1 U981 (.Y(\add_581/carry[7] ),
	.B(\add_581/carry[6] ),
	.A(pixel_num[6]));
   XNOR2X1 U982 (.Y(N401),
	.B(pixel_num[6]),
	.A(\add_581/carry[6] ));
   OR2X1 U983 (.Y(\add_581/carry[6] ),
	.B(\add_581/carry[5] ),
	.A(pixel_num[5]));
   XNOR2X1 U984 (.Y(N400),
	.B(pixel_num[5]),
	.A(\add_581/carry[5] ));
   AND2X1 U985 (.Y(\add_581/carry[5] ),
	.B(pixel_num[4]),
	.A(\add_581/carry[4] ));
   XOR2X1 U986 (.Y(N399),
	.B(\add_581/carry[4] ),
	.A(pixel_num[4]));
   AND2X1 U987 (.Y(\add_581/carry[4] ),
	.B(pixel_num[3]),
	.A(\add_581/carry[3] ));
   XOR2X1 U988 (.Y(N398),
	.B(\add_581/carry[3] ),
	.A(pixel_num[3]));
   AND2X1 U989 (.Y(\add_581/carry[3] ),
	.B(pixel_num[2]),
	.A(\add_581/carry[2] ));
   XOR2X1 U990 (.Y(N397),
	.B(\add_581/carry[2] ),
	.A(pixel_num[2]));
   AND2X1 U991 (.Y(\add_581/carry[2] ),
	.B(pixel_num[1]),
	.A(pixel_num[0]));
   XOR2X1 U992 (.Y(N396),
	.B(pixel_num[0]),
	.A(pixel_num[1]));
   XOR2X1 U993 (.Y(N423),
	.B(\add_583/carry[13] ),
	.A(pixel_num[13]));
   AND2X1 U994 (.Y(\add_583/carry[13] ),
	.B(pixel_num[12]),
	.A(\add_583/carry[12] ));
   XOR2X1 U995 (.Y(N422),
	.B(\add_583/carry[12] ),
	.A(pixel_num[12]));
   AND2X1 U996 (.Y(\add_583/carry[12] ),
	.B(pixel_num[11]),
	.A(\add_583/carry[11] ));
   XOR2X1 U997 (.Y(N421),
	.B(\add_583/carry[11] ),
	.A(pixel_num[11]));
   AND2X1 U998 (.Y(\add_583/carry[11] ),
	.B(pixel_num[10]),
	.A(\add_583/carry[10] ));
   XOR2X1 U999 (.Y(N420),
	.B(\add_583/carry[10] ),
	.A(pixel_num[10]));
   AND2X1 U1000 (.Y(\add_583/carry[10] ),
	.B(pixel_num[9]),
	.A(\add_583/carry[9] ));
   XOR2X1 U1001 (.Y(N419),
	.B(\add_583/carry[9] ),
	.A(pixel_num[9]));
   AND2X1 U1002 (.Y(\add_583/carry[9] ),
	.B(pixel_num[8]),
	.A(\add_583/carry[8] ));
   XOR2X1 U1003 (.Y(N418),
	.B(\add_583/carry[8] ),
	.A(pixel_num[8]));
   AND2X1 U1004 (.Y(\add_583/carry[8] ),
	.B(pixel_num[7]),
	.A(\add_583/carry[7] ));
   XOR2X1 U1005 (.Y(N417),
	.B(\add_583/carry[7] ),
	.A(pixel_num[7]));
   OR2X1 U1006 (.Y(\add_583/carry[7] ),
	.B(\add_583/carry[6] ),
	.A(pixel_num[6]));
   XNOR2X1 U1007 (.Y(N416),
	.B(pixel_num[6]),
	.A(\add_583/carry[6] ));
   AND2X1 U1008 (.Y(\add_583/carry[6] ),
	.B(pixel_num[5]),
	.A(\add_583/carry[5] ));
   XOR2X1 U1009 (.Y(N415),
	.B(\add_583/carry[5] ),
	.A(pixel_num[5]));
   AND2X1 U1010 (.Y(\add_583/carry[5] ),
	.B(pixel_num[4]),
	.A(\add_583/carry[4] ));
   XOR2X1 U1011 (.Y(N414),
	.B(\add_583/carry[4] ),
	.A(pixel_num[4]));
   AND2X1 U1012 (.Y(\add_583/carry[4] ),
	.B(pixel_num[3]),
	.A(\add_583/carry[3] ));
   XOR2X1 U1013 (.Y(N413),
	.B(\add_583/carry[3] ),
	.A(pixel_num[3]));
   AND2X1 U1014 (.Y(\add_583/carry[3] ),
	.B(pixel_num[2]),
	.A(\add_581/carry[2] ));
   XOR2X1 U1018 (.Y(N393),
	.B(\add_579/carry[13] ),
	.A(pixel_num[13]));
   AND2X1 U1019 (.Y(\add_579/carry[13] ),
	.B(pixel_num[12]),
	.A(\add_579/carry[12] ));
   XOR2X1 U1020 (.Y(N392),
	.B(\add_579/carry[12] ),
	.A(pixel_num[12]));
   AND2X1 U1021 (.Y(\add_579/carry[12] ),
	.B(pixel_num[11]),
	.A(\add_579/carry[11] ));
   XOR2X1 U1022 (.Y(N391),
	.B(\add_579/carry[11] ),
	.A(pixel_num[11]));
   AND2X1 U1023 (.Y(\add_579/carry[11] ),
	.B(pixel_num[10]),
	.A(\add_579/carry[10] ));
   XOR2X1 U1024 (.Y(N390),
	.B(\add_579/carry[10] ),
	.A(pixel_num[10]));
   AND2X1 U1025 (.Y(\add_579/carry[10] ),
	.B(pixel_num[9]),
	.A(\add_579/carry[9] ));
   XOR2X1 U1026 (.Y(N389),
	.B(\add_579/carry[9] ),
	.A(pixel_num[9]));
   AND2X1 U1027 (.Y(\add_579/carry[9] ),
	.B(pixel_num[8]),
	.A(\add_579/carry[8] ));
   XOR2X1 U1028 (.Y(N388),
	.B(\add_579/carry[8] ),
	.A(pixel_num[8]));
   AND2X1 U1029 (.Y(\add_579/carry[8] ),
	.B(pixel_num[7]),
	.A(\add_579/carry[7] ));
   XOR2X1 U1030 (.Y(N387),
	.B(\add_579/carry[7] ),
	.A(pixel_num[7]));
   OR2X1 U1031 (.Y(\add_579/carry[7] ),
	.B(\add_579/carry[6] ),
	.A(pixel_num[6]));
   XNOR2X1 U1032 (.Y(N386),
	.B(pixel_num[6]),
	.A(\add_579/carry[6] ));
   OR2X1 U1033 (.Y(\add_579/carry[6] ),
	.B(\add_579/carry[5] ),
	.A(pixel_num[5]));
   XNOR2X1 U1034 (.Y(N385),
	.B(pixel_num[5]),
	.A(\add_579/carry[5] ));
   OR2X1 U1035 (.Y(\add_579/carry[5] ),
	.B(\add_579/carry[4] ),
	.A(pixel_num[4]));
   XNOR2X1 U1036 (.Y(N384),
	.B(pixel_num[4]),
	.A(\add_579/carry[4] ));
   AND2X1 U1037 (.Y(\add_579/carry[4] ),
	.B(pixel_num[3]),
	.A(\add_579/carry[3] ));
   XOR2X1 U1038 (.Y(N383),
	.B(\add_579/carry[3] ),
	.A(pixel_num[3]));
   AND2X1 U1039 (.Y(\add_579/carry[3] ),
	.B(pixel_num[2]),
	.A(\add_579/carry[2] ));
   XOR2X1 U1040 (.Y(N382),
	.B(\add_579/carry[2] ),
	.A(pixel_num[2]));
   AND2X1 U1041 (.Y(\add_579/carry[2] ),
	.B(pixel_num[1]),
	.A(pixel_num[0]));
endmodule

